### ISSUE TITLE
Separated "Gnorm" phase?

### ISSUE THREAD

**Issue by EJShim** [magic-research/GETAvatar#2]
Hello, Thank you for your greate work.

I have a question on the training code.
I can see that "Gmain" and "Gnorm" phase are separated.
Isn't normal map can be generated during "Gmain"  phase? 

Is there a reason you have separated normal and texture generation?

**Comment by Xuanmeng-Zhang** [comment]
The normal map can also be generated during "Gmain" phase. We separated normal and texture generation during training to reduce the GPU memory cost.
